USE [master]
GO
/****** Object:  Database [HR]    Script Date: 2/5/2023 9:27:22 PM ******/
CREATE DATABASE [HR]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'HumanResourses', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\HumanResourses.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'HumanResourses_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\HumanResourses_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [HR] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [HR].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [HR] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [HR] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [HR] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [HR] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [HR] SET ARITHABORT OFF 
GO
ALTER DATABASE [HR] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [HR] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [HR] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [HR] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [HR] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [HR] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [HR] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [HR] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [HR] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [HR] SET  DISABLE_BROKER 
GO
ALTER DATABASE [HR] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [HR] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [HR] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [HR] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [HR] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [HR] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [HR] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [HR] SET RECOVERY FULL 
GO
ALTER DATABASE [HR] SET  MULTI_USER 
GO
ALTER DATABASE [HR] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [HR] SET DB_CHAINING OFF 
GO
ALTER DATABASE [HR] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [HR] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [HR] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [HR] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'HR', N'ON'
GO
ALTER DATABASE [HR] SET QUERY_STORE = OFF
GO
USE [HR]
GO
/****** Object:  Table [dbo].[Benfits]    Script Date: 2/5/2023 9:27:28 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Benfits](
	[BenfitId] [int] IDENTITY(1,1) NOT NULL,
	[BenfitDesc] [varchar](50) NOT NULL,
	[IsActive] [bit] NULL,
PRIMARY KEY CLUSTERED 
(
	[BenfitId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Department]    Script Date: 2/5/2023 9:27:28 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Department](
	[DeptId] [int] IDENTITY(1,1) NOT NULL,
	[DeptEName] [varchar](50) NOT NULL,
	[DeptManagerId] [int] NULL,
	[DeptAName] [nvarchar](50) NOT NULL,
	[IsActive] [bit] NOT NULL,
 CONSTRAINT [PK__Departme__014881AEDBD8FE37] PRIMARY KEY CLUSTERED 
(
	[DeptId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[EmpHistory]    Script Date: 2/5/2023 9:27:28 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[EmpHistory](
	[EmpId] [int] NULL,
	[TitleId] [int] NULL,
	[GradeId] [int] NULL,
	[SectionId] [int] NULL,
	[Managerid] [int] NULL,
	[Address] [nvarchar](50) NULL,
	[PhoneNo] [nchar](12) NULL,
	[Email] [varchar](50) NULL,
	[ChangeDate] [datetime2](7) NULL,
	[Salary] [decimal](10, 3) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Employee]    Script Date: 2/5/2023 9:27:28 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Employee](
	[EmpId] [int] IDENTITY(1,1) NOT NULL,
	[FirstName] [nvarchar](50) NOT NULL,
	[ManagerId] [int] NULL,
	[TitleId] [int] NULL,
	[GradeId] [int] NULL,
	[SectionId] [int] NULL,
	[HireDate] [date] NOT NULL,
	[LastName] [nvarchar](50) NULL,
	[PhoneNo] [nchar](12) NOT NULL,
	[Email] [varchar](50) NOT NULL,
	[DOB] [date] NOT NULL,
	[Address] [nvarchar](50) NULL,
	[Gender] [char](1) NOT NULL,
	[NationalNo] [char](10) NOT NULL,
	[IsActive] [bit] NOT NULL,
	[Salary] [decimal](10, 3) NOT NULL,
 CONSTRAINT [PK__Employee__AF2DBB99ACF65D53] PRIMARY KEY CLUSTERED 
(
	[EmpId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Grade]    Script Date: 2/5/2023 9:27:28 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Grade](
	[GradeId] [int] IDENTITY(1,1) NOT NULL,
	[GradeEDesc] [varchar](50) NOT NULL,
	[GradeADesc] [varchar](50) NOT NULL,
	[IsActive] [bit] NOT NULL,
 CONSTRAINT [PK__Grade__54F87A57213DB27D] PRIMARY KEY CLUSTERED 
(
	[GradeId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[GradeBenfit]    Script Date: 2/5/2023 9:27:28 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[GradeBenfit](
	[BeniftId] [int] NULL,
	[GradeId] [int] NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Sections]    Script Date: 2/5/2023 9:27:28 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Sections](
	[SectionId] [int] IDENTITY(1,1) NOT NULL,
	[SectionEName] [varchar](50) NOT NULL,
	[SectionManagerId] [int] NULL,
	[DeptId] [int] NULL,
	[DeptAName] [nvarchar](50) NOT NULL,
	[IsActive] [bit] NOT NULL,
 CONSTRAINT [PK__Sections__80EF08725B211E69] PRIMARY KEY CLUSTERED 
(
	[SectionId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Title]    Script Date: 2/5/2023 9:27:28 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Title](
	[TitleId] [int] IDENTITY(1,1) NOT NULL,
	[TitleEDesc] [varchar](50) NOT NULL,
	[TitleADesc] [nvarchar](50) NOT NULL,
	[IsActive] [bit] NOT NULL,
 CONSTRAINT [PK__Title__75758986204EAA17] PRIMARY KEY CLUSTERED 
(
	[TitleId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Department]  WITH CHECK ADD  CONSTRAINT [depemp_fk] FOREIGN KEY([DeptManagerId])
REFERENCES [dbo].[Employee] ([EmpId])
GO
ALTER TABLE [dbo].[Department] CHECK CONSTRAINT [depemp_fk]
GO
ALTER TABLE [dbo].[EmpHistory]  WITH CHECK ADD  CONSTRAINT [EmpHistory_fk] FOREIGN KEY([Managerid])
REFERENCES [dbo].[Employee] ([EmpId])
GO
ALTER TABLE [dbo].[EmpHistory] CHECK CONSTRAINT [EmpHistory_fk]
GO
ALTER TABLE [dbo].[EmpHistory]  WITH CHECK ADD  CONSTRAINT [FK__EmpHistor__EmpId__403A8C7D] FOREIGN KEY([EmpId])
REFERENCES [dbo].[Employee] ([EmpId])
GO
ALTER TABLE [dbo].[EmpHistory] CHECK CONSTRAINT [FK__EmpHistor__EmpId__403A8C7D]
GO
ALTER TABLE [dbo].[EmpHistory]  WITH CHECK ADD  CONSTRAINT [FK__EmpHistor__Grade__4222D4EF] FOREIGN KEY([GradeId])
REFERENCES [dbo].[Grade] ([GradeId])
GO
ALTER TABLE [dbo].[EmpHistory] CHECK CONSTRAINT [FK__EmpHistor__Grade__4222D4EF]
GO
ALTER TABLE [dbo].[EmpHistory]  WITH CHECK ADD  CONSTRAINT [FK__EmpHistor__Manag__440B1D61] FOREIGN KEY([Managerid])
REFERENCES [dbo].[Employee] ([EmpId])
GO
ALTER TABLE [dbo].[EmpHistory] CHECK CONSTRAINT [FK__EmpHistor__Manag__440B1D61]
GO
ALTER TABLE [dbo].[EmpHistory]  WITH CHECK ADD  CONSTRAINT [FK__EmpHistor__Secti__4316F928] FOREIGN KEY([SectionId])
REFERENCES [dbo].[Sections] ([SectionId])
GO
ALTER TABLE [dbo].[EmpHistory] CHECK CONSTRAINT [FK__EmpHistor__Secti__4316F928]
GO
ALTER TABLE [dbo].[EmpHistory]  WITH CHECK ADD  CONSTRAINT [FK__EmpHistor__Title__412EB0B6] FOREIGN KEY([TitleId])
REFERENCES [dbo].[Title] ([TitleId])
GO
ALTER TABLE [dbo].[EmpHistory] CHECK CONSTRAINT [FK__EmpHistor__Title__412EB0B6]
GO
ALTER TABLE [dbo].[Employee]  WITH CHECK ADD  CONSTRAINT [FK__Employee__GradeI__3C69FB99] FOREIGN KEY([GradeId])
REFERENCES [dbo].[Grade] ([GradeId])
GO
ALTER TABLE [dbo].[Employee] CHECK CONSTRAINT [FK__Employee__GradeI__3C69FB99]
GO
ALTER TABLE [dbo].[Employee]  WITH CHECK ADD  CONSTRAINT [FK__Employee__Manage__3A81B327] FOREIGN KEY([ManagerId])
REFERENCES [dbo].[Employee] ([EmpId])
GO
ALTER TABLE [dbo].[Employee] CHECK CONSTRAINT [FK__Employee__Manage__3A81B327]
GO
ALTER TABLE [dbo].[Employee]  WITH CHECK ADD  CONSTRAINT [FK__Employee__Sectio__3D5E1FD2] FOREIGN KEY([SectionId])
REFERENCES [dbo].[Sections] ([SectionId])
GO
ALTER TABLE [dbo].[Employee] CHECK CONSTRAINT [FK__Employee__Sectio__3D5E1FD2]
GO
ALTER TABLE [dbo].[Employee]  WITH CHECK ADD  CONSTRAINT [FK__Employee__TitleI__3B75D760] FOREIGN KEY([TitleId])
REFERENCES [dbo].[Title] ([TitleId])
GO
ALTER TABLE [dbo].[Employee] CHECK CONSTRAINT [FK__Employee__TitleI__3B75D760]
GO
ALTER TABLE [dbo].[GradeBenfit]  WITH CHECK ADD FOREIGN KEY([BeniftId])
REFERENCES [dbo].[Benfits] ([BenfitId])
GO
ALTER TABLE [dbo].[GradeBenfit]  WITH CHECK ADD  CONSTRAINT [FK__GradeBenf__Grade__35BCFE0A] FOREIGN KEY([GradeId])
REFERENCES [dbo].[Grade] ([GradeId])
GO
ALTER TABLE [dbo].[GradeBenfit] CHECK CONSTRAINT [FK__GradeBenf__Grade__35BCFE0A]
GO
ALTER TABLE [dbo].[Sections]  WITH CHECK ADD  CONSTRAINT [FK__Sections__DeptId__30F848ED] FOREIGN KEY([DeptId])
REFERENCES [dbo].[Department] ([DeptId])
GO
ALTER TABLE [dbo].[Sections] CHECK CONSTRAINT [FK__Sections__DeptId__30F848ED]
GO
ALTER TABLE [dbo].[Sections]  WITH CHECK ADD  CONSTRAINT [secemp_fk] FOREIGN KEY([SectionManagerId])
REFERENCES [dbo].[Employee] ([EmpId])
GO
ALTER TABLE [dbo].[Sections] CHECK CONSTRAINT [secemp_fk]
GO
ALTER TABLE [dbo].[EmpHistory]  WITH CHECK ADD CHECK  (([salary]>(0)))
GO
ALTER TABLE [dbo].[Employee]  WITH CHECK ADD  CONSTRAINT [CK__Employee__Salary__3E52440B] CHECK  (([salary]>(0)))
GO
ALTER TABLE [dbo].[Employee] CHECK CONSTRAINT [CK__Employee__Salary__3E52440B]
GO
USE [master]
GO
ALTER DATABASE [HR] SET  READ_WRITE 
GO
